apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      # l7-xlb-basic-check-http is using the root path for health checking
      - exact: /
      options:
        prefixRewrite: /api/pets
        # Because the cluster uses spot nodes that can be shut down at any time, having a retry mechanism
        # is a good idea in case the pod/node shutdown process isn't clean leaving the possibility of request failures
        retries:
          retryOn: 'connect-failure'
          numRetries: 3
          perTryTimeout: '1s'
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petstore
  name: petstore
  namespace: default
spec:
  selector:
    matchLabels:
      app: petstore
  replicas: 2
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
      - image: soloio/petstore-example:latest
        name: petstore
        ports:
        - containerPort: 8080
          name: http
      affinity:
        # Because the cluster uses spot nodes that can be shut down at any time, having at least
        # 2 replicas with antiAffinity is needed for application resilency when a node shuts down
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - petstore
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: petstore
  namespace: default
  labels:
    service: petstore
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: petstore